#!/usr/bin/env python3
"""
Practical Usage Example for Dynamic Location Management
"""
print('🛠️ PRACTICAL USAGE EXAMPLE - STEP BY STEP')
print('=' * 50)
print()
print('🎯 SCENARIO: Adding Stellenbosch for flood monitoring')
print()
print('STEP 1: GEOCODE ADDRESS')
print('POST /api/v1/locations/geocode')
print('Body: {"query": "Stellenbosch, South Africa", "limit": 3}')
print('→ Returns coordinates and location details')
print()
print('STEP 2: CREATE LOCATION')
print('POST /api/v1/locations')
print('Body: {')
print('  "name": "Stellenbosch",')
print('  "latitude": -33.9346,')
print('  "longitude": 18.8668,')
print('  "region": "Western Cape",')
print('  "tags": ["university", "wine-region"]')
print('}')
print('→ Returns location_id for future reference')
print()
print('STEP 3: COLLECT WEATHER')
print('GET /api/v1/weather/collect?location_ids={location_id}')
print('→ Fetches weather for Stellenbosch')
print()
print('STEP 4: GET PREDICTIONS')
print('POST /api/v1/risk/predict')
print('→ Includes Stellenbosch in flood risk assessment')
print()
print('STEP 5: SEARCH LOCATIONS')
print('POST /api/v1/locations/search')
print('Body: {"region": "Western Cape", "limit": 10}')
print('→ Finds all Western Cape locations including Stellenbosch')
print()
print('STEP 6: CREATE PRESET')
print('POST /api/v1/locations/presets')
print('Body: {')
print('  "name": "Western Cape Emergency",')
print('  "locations": ["{location_id}"],')
print('  "category": "emergency"')
print('}')
print('→ Creates reusable location collection')
print()
print('🎉 RESULT: Stellenbosch integrated into monitoring system!')
print()
print('💡 KEY BENEFITS:')
print('• No code changes needed to add locations')
print('• Rich metadata for better decision making')
print('• Automatic geocoding for easy setup')
print('• Flexible search and filtering')
print('• Preset collections for common scenarios')
print('• Seamless integration with prediction system')
